version: "2"
linters:
  enable:
    - containedctx
    - dupl
    - durationcheck
    - errname
    - exhaustive
    - forcetypeassert
    - godot
    - goheader
    - goprintffuncname
    - gosec
    - musttag
    - nestif
    - nolintlint
    - nosprintfhostport
    - prealloc
    - predeclared
    - reassign
    - revive
    - testableexamples
    - unconvert
    - usestdlibvars
    - whitespace
    - wsl_v5
  disable:
    - depguard
  settings:
    revive:
      rules:
        - name: blank-imports
          disabled: true
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
      enable:
        - assign-expr
      disable:
        - append
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
        path: ent/.*\.go
      - path: (.+)\.go$
        text: if statements should only be cuddled with assignments
      - path: (.+)\.go$
        text: if statements should only be cuddled with assignments used in the if statement itself
      - path: (.+)\.go$
        text: assignments should only be cuddled with other assignments
      - path: (.+)\.go$
        text: declarations should never be cuddled
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
