version: "3.9"

services:
  insights_bot:
    image: ghcr.io/nekomeowww/insights-bot:latest
    restart: always
    environment:
      - TELEGRAM_BOT_TOKEN
      - OPENAI_API_SECRET
      - OPENAI_API_HOST
      - SLACK_CLIENT_ID
      - SLACK_CLIENT_SECRET
      - DB_CONNECTION_STR=postgresql://postgres:123456@db_local:5432/postgres?search_path=public&sslmode=disable
    ports:
      - 7070:7070
    profiles:
      - hub

  insights_bot_local:
    image: insights-bot
    restart: always
    environment:
      - TELEGRAM_BOT_TOKEN
      - OPENAI_API_SECRET
      - OPENAI_API_HOST
      - SLACK_CLIENT_ID
      - SLACK_CLIENT_SECRET
      - DB_CONNECTION_STR=postgresql://postgres:123456@db_local:5432/postgres?search_path=public&sslmode=disable
    ports:
      - 7070:7070
    build:
      context: .
      dockerfile: ./Dockerfile
    profiles:
      - local

  db_local:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./.postgres/data:/var/lib/postgresql/data
