version: "3.9"

services:
  insights_bot:
    image: nekomeowww/insights-bot:latest
    restart: always
    environment:
      - TELEGRAM_BOT_TOKEN=<Telegram Bot API Token>
      - OPENAI_API_SECRET=<OpenAI API Secret Key>
      - DB_CONNECTION_STR=<PostgresSQL database URL>
      # - SLACK_BOT_TOKEN=<Slack Bot User OAuth Token> # optional, uncomment this if you want to enable slack integration
      # - OPENAI_API_HOST=https://<Some Host> # uncomment this if you want to use your own OpenAI API host
    ports:
      - 7070:7070
    profiles:
      - hub

  insights_bot_local:
    image: insights-bot
    restart: always
    environment:
      - TELEGRAM_BOT_TOKEN=<Telegram Bot API Token>
      - OPENAI_API_SECRET=<OpenAI API Secret Key>
      - DB_CONNECTION_STR=<PostgresSQL database URL>
      # - SLACK_BOT_TOKEN=<Slack Bot User OAuth Token> # optional, uncomment this if you want to enable slack integration
      # - OPENAI_API_HOST=https://<Some Host> # uncomment this if you want to use your own OpenAI API host
    ports:
      - 7070:7070
    build:
      context: .
      dockerfile: ./Dockerfile
    profiles:
      - local
