// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/nekomeowww/insights-bot/ent/chathistories"
	"github.com/nekomeowww/insights-bot/ent/internal"
	"github.com/nekomeowww/insights-bot/ent/predicate"
)

// ChatHistoriesDelete is the builder for deleting a ChatHistories entity.
type ChatHistoriesDelete struct {
	config
	hooks    []Hook
	mutation *ChatHistoriesMutation
}

// Where appends a list predicates to the ChatHistoriesDelete builder.
func (chd *ChatHistoriesDelete) Where(ps ...predicate.ChatHistories) *ChatHistoriesDelete {
	chd.mutation.Where(ps...)
	return chd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (chd *ChatHistoriesDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, chd.sqlExec, chd.mutation, chd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (chd *ChatHistoriesDelete) ExecX(ctx context.Context) int {
	n, err := chd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (chd *ChatHistoriesDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(chathistories.Table, sqlgraph.NewFieldSpec(chathistories.FieldID, field.TypeUUID))
	_spec.Node.Schema = chd.schemaConfig.ChatHistories
	ctx = internal.NewSchemaConfigContext(ctx, chd.schemaConfig)
	if ps := chd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, chd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	chd.mutation.done = true
	return affected, err
}

// ChatHistoriesDeleteOne is the builder for deleting a single ChatHistories entity.
type ChatHistoriesDeleteOne struct {
	chd *ChatHistoriesDelete
}

// Where appends a list predicates to the ChatHistoriesDelete builder.
func (chdo *ChatHistoriesDeleteOne) Where(ps ...predicate.ChatHistories) *ChatHistoriesDeleteOne {
	chdo.chd.mutation.Where(ps...)
	return chdo
}

// Exec executes the deletion query.
func (chdo *ChatHistoriesDeleteOne) Exec(ctx context.Context) error {
	n, err := chdo.chd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{chathistories.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (chdo *ChatHistoriesDeleteOne) ExecX(ctx context.Context) {
	if err := chdo.Exec(ctx); err != nil {
		panic(err)
	}
}
