// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/nekomeowww/insights-bot/ent/feedbackchathistoriesrecapsreactions"
	"github.com/nekomeowww/insights-bot/ent/internal"
	"github.com/nekomeowww/insights-bot/ent/predicate"
)

// FeedbackChatHistoriesRecapsReactionsDelete is the builder for deleting a FeedbackChatHistoriesRecapsReactions entity.
type FeedbackChatHistoriesRecapsReactionsDelete struct {
	config
	hooks    []Hook
	mutation *FeedbackChatHistoriesRecapsReactionsMutation
}

// Where appends a list predicates to the FeedbackChatHistoriesRecapsReactionsDelete builder.
func (_d *FeedbackChatHistoriesRecapsReactionsDelete) Where(ps ...predicate.FeedbackChatHistoriesRecapsReactions) *FeedbackChatHistoriesRecapsReactionsDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *FeedbackChatHistoriesRecapsReactionsDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *FeedbackChatHistoriesRecapsReactionsDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *FeedbackChatHistoriesRecapsReactionsDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(feedbackchathistoriesrecapsreactions.Table, sqlgraph.NewFieldSpec(feedbackchathistoriesrecapsreactions.FieldID, field.TypeUUID))
	_spec.Node.Schema = _d.schemaConfig.FeedbackChatHistoriesRecapsReactions
	ctx = internal.NewSchemaConfigContext(ctx, _d.schemaConfig)
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// FeedbackChatHistoriesRecapsReactionsDeleteOne is the builder for deleting a single FeedbackChatHistoriesRecapsReactions entity.
type FeedbackChatHistoriesRecapsReactionsDeleteOne struct {
	_d *FeedbackChatHistoriesRecapsReactionsDelete
}

// Where appends a list predicates to the FeedbackChatHistoriesRecapsReactionsDelete builder.
func (_d *FeedbackChatHistoriesRecapsReactionsDeleteOne) Where(ps ...predicate.FeedbackChatHistoriesRecapsReactions) *FeedbackChatHistoriesRecapsReactionsDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *FeedbackChatHistoriesRecapsReactionsDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{feedbackchathistoriesrecapsreactions.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *FeedbackChatHistoriesRecapsReactionsDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
