// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/nekomeowww/insights-bot/ent/internal"
	"github.com/nekomeowww/insights-bot/ent/predicate"
	"github.com/nekomeowww/insights-bot/ent/savedslacktoken"
)

// SavedSlackTokenQuery is the builder for querying SavedSlackToken entities.
type SavedSlackTokenQuery struct {
	config
	ctx        *QueryContext
	order      []savedslacktoken.OrderOption
	inters     []Interceptor
	predicates []predicate.SavedSlackToken
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SavedSlackTokenQuery builder.
func (sstq *SavedSlackTokenQuery) Where(ps ...predicate.SavedSlackToken) *SavedSlackTokenQuery {
	sstq.predicates = append(sstq.predicates, ps...)
	return sstq
}

// Limit the number of records to be returned by this query.
func (sstq *SavedSlackTokenQuery) Limit(limit int) *SavedSlackTokenQuery {
	sstq.ctx.Limit = &limit
	return sstq
}

// Offset to start from.
func (sstq *SavedSlackTokenQuery) Offset(offset int) *SavedSlackTokenQuery {
	sstq.ctx.Offset = &offset
	return sstq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (sstq *SavedSlackTokenQuery) Unique(unique bool) *SavedSlackTokenQuery {
	sstq.ctx.Unique = &unique
	return sstq
}

// Order specifies how the records should be ordered.
func (sstq *SavedSlackTokenQuery) Order(o ...savedslacktoken.OrderOption) *SavedSlackTokenQuery {
	sstq.order = append(sstq.order, o...)
	return sstq
}

// First returns the first SavedSlackToken entity from the query.
// Returns a *NotFoundError when no SavedSlackToken was found.
func (sstq *SavedSlackTokenQuery) First(ctx context.Context) (*SavedSlackToken, error) {
	nodes, err := sstq.Limit(1).All(setContextOp(ctx, sstq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{savedslacktoken.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (sstq *SavedSlackTokenQuery) FirstX(ctx context.Context) *SavedSlackToken {
	node, err := sstq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first SavedSlackToken ID from the query.
// Returns a *NotFoundError when no SavedSlackToken ID was found.
func (sstq *SavedSlackTokenQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = sstq.Limit(1).IDs(setContextOp(ctx, sstq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{savedslacktoken.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (sstq *SavedSlackTokenQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := sstq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single SavedSlackToken entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one SavedSlackToken entity is found.
// Returns a *NotFoundError when no SavedSlackToken entities are found.
func (sstq *SavedSlackTokenQuery) Only(ctx context.Context) (*SavedSlackToken, error) {
	nodes, err := sstq.Limit(2).All(setContextOp(ctx, sstq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{savedslacktoken.Label}
	default:
		return nil, &NotSingularError{savedslacktoken.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (sstq *SavedSlackTokenQuery) OnlyX(ctx context.Context) *SavedSlackToken {
	node, err := sstq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only SavedSlackToken ID in the query.
// Returns a *NotSingularError when more than one SavedSlackToken ID is found.
// Returns a *NotFoundError when no entities are found.
func (sstq *SavedSlackTokenQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = sstq.Limit(2).IDs(setContextOp(ctx, sstq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{savedslacktoken.Label}
	default:
		err = &NotSingularError{savedslacktoken.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (sstq *SavedSlackTokenQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := sstq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SavedSlackTokens.
func (sstq *SavedSlackTokenQuery) All(ctx context.Context) ([]*SavedSlackToken, error) {
	ctx = setContextOp(ctx, sstq.ctx, "All")
	if err := sstq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*SavedSlackToken, *SavedSlackTokenQuery]()
	return withInterceptors[[]*SavedSlackToken](ctx, sstq, qr, sstq.inters)
}

// AllX is like All, but panics if an error occurs.
func (sstq *SavedSlackTokenQuery) AllX(ctx context.Context) []*SavedSlackToken {
	nodes, err := sstq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of SavedSlackToken IDs.
func (sstq *SavedSlackTokenQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if sstq.ctx.Unique == nil && sstq.path != nil {
		sstq.Unique(true)
	}
	ctx = setContextOp(ctx, sstq.ctx, "IDs")
	if err = sstq.Select(savedslacktoken.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (sstq *SavedSlackTokenQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := sstq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (sstq *SavedSlackTokenQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, sstq.ctx, "Count")
	if err := sstq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, sstq, querierCount[*SavedSlackTokenQuery](), sstq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (sstq *SavedSlackTokenQuery) CountX(ctx context.Context) int {
	count, err := sstq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (sstq *SavedSlackTokenQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, sstq.ctx, "Exist")
	switch _, err := sstq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (sstq *SavedSlackTokenQuery) ExistX(ctx context.Context) bool {
	exist, err := sstq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SavedSlackTokenQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (sstq *SavedSlackTokenQuery) Clone() *SavedSlackTokenQuery {
	if sstq == nil {
		return nil
	}
	return &SavedSlackTokenQuery{
		config:     sstq.config,
		ctx:        sstq.ctx.Clone(),
		order:      append([]savedslacktoken.OrderOption{}, sstq.order...),
		inters:     append([]Interceptor{}, sstq.inters...),
		predicates: append([]predicate.SavedSlackToken{}, sstq.predicates...),
		// clone intermediate query.
		sql:  sstq.sql.Clone(),
		path: sstq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		TeamID string `json:"team_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.SavedSlackToken.Query().
//		GroupBy(savedslacktoken.FieldTeamID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (sstq *SavedSlackTokenQuery) GroupBy(field string, fields ...string) *SavedSlackTokenGroupBy {
	sstq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SavedSlackTokenGroupBy{build: sstq}
	grbuild.flds = &sstq.ctx.Fields
	grbuild.label = savedslacktoken.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		TeamID string `json:"team_id,omitempty"`
//	}
//
//	client.SavedSlackToken.Query().
//		Select(savedslacktoken.FieldTeamID).
//		Scan(ctx, &v)
func (sstq *SavedSlackTokenQuery) Select(fields ...string) *SavedSlackTokenSelect {
	sstq.ctx.Fields = append(sstq.ctx.Fields, fields...)
	sbuild := &SavedSlackTokenSelect{SavedSlackTokenQuery: sstq}
	sbuild.label = savedslacktoken.Label
	sbuild.flds, sbuild.scan = &sstq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SavedSlackTokenSelect configured with the given aggregations.
func (sstq *SavedSlackTokenQuery) Aggregate(fns ...AggregateFunc) *SavedSlackTokenSelect {
	return sstq.Select().Aggregate(fns...)
}

func (sstq *SavedSlackTokenQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range sstq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, sstq); err != nil {
				return err
			}
		}
	}
	for _, f := range sstq.ctx.Fields {
		if !savedslacktoken.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if sstq.path != nil {
		prev, err := sstq.path(ctx)
		if err != nil {
			return err
		}
		sstq.sql = prev
	}
	return nil
}

func (sstq *SavedSlackTokenQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*SavedSlackToken, error) {
	var (
		nodes = []*SavedSlackToken{}
		_spec = sstq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*SavedSlackToken).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &SavedSlackToken{config: sstq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	_spec.Node.Schema = sstq.schemaConfig.SavedSlackToken
	ctx = internal.NewSchemaConfigContext(ctx, sstq.schemaConfig)
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, sstq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (sstq *SavedSlackTokenQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := sstq.querySpec()
	_spec.Node.Schema = sstq.schemaConfig.SavedSlackToken
	ctx = internal.NewSchemaConfigContext(ctx, sstq.schemaConfig)
	_spec.Node.Columns = sstq.ctx.Fields
	if len(sstq.ctx.Fields) > 0 {
		_spec.Unique = sstq.ctx.Unique != nil && *sstq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, sstq.driver, _spec)
}

func (sstq *SavedSlackTokenQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(savedslacktoken.Table, savedslacktoken.Columns, sqlgraph.NewFieldSpec(savedslacktoken.FieldID, field.TypeUUID))
	_spec.From = sstq.sql
	if unique := sstq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if sstq.path != nil {
		_spec.Unique = true
	}
	if fields := sstq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, savedslacktoken.FieldID)
		for i := range fields {
			if fields[i] != savedslacktoken.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := sstq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := sstq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := sstq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := sstq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (sstq *SavedSlackTokenQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(sstq.driver.Dialect())
	t1 := builder.Table(savedslacktoken.Table)
	columns := sstq.ctx.Fields
	if len(columns) == 0 {
		columns = savedslacktoken.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if sstq.sql != nil {
		selector = sstq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if sstq.ctx.Unique != nil && *sstq.ctx.Unique {
		selector.Distinct()
	}
	t1.Schema(sstq.schemaConfig.SavedSlackToken)
	ctx = internal.NewSchemaConfigContext(ctx, sstq.schemaConfig)
	selector.WithContext(ctx)
	for _, p := range sstq.predicates {
		p(selector)
	}
	for _, p := range sstq.order {
		p(selector)
	}
	if offset := sstq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := sstq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// SavedSlackTokenGroupBy is the group-by builder for SavedSlackToken entities.
type SavedSlackTokenGroupBy struct {
	selector
	build *SavedSlackTokenQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (sstgb *SavedSlackTokenGroupBy) Aggregate(fns ...AggregateFunc) *SavedSlackTokenGroupBy {
	sstgb.fns = append(sstgb.fns, fns...)
	return sstgb
}

// Scan applies the selector query and scans the result into the given value.
func (sstgb *SavedSlackTokenGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sstgb.build.ctx, "GroupBy")
	if err := sstgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SavedSlackTokenQuery, *SavedSlackTokenGroupBy](ctx, sstgb.build, sstgb, sstgb.build.inters, v)
}

func (sstgb *SavedSlackTokenGroupBy) sqlScan(ctx context.Context, root *SavedSlackTokenQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(sstgb.fns))
	for _, fn := range sstgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*sstgb.flds)+len(sstgb.fns))
		for _, f := range *sstgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*sstgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sstgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SavedSlackTokenSelect is the builder for selecting fields of SavedSlackToken entities.
type SavedSlackTokenSelect struct {
	*SavedSlackTokenQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ssts *SavedSlackTokenSelect) Aggregate(fns ...AggregateFunc) *SavedSlackTokenSelect {
	ssts.fns = append(ssts.fns, fns...)
	return ssts
}

// Scan applies the selector query and scans the result into the given value.
func (ssts *SavedSlackTokenSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ssts.ctx, "Select")
	if err := ssts.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SavedSlackTokenQuery, *SavedSlackTokenSelect](ctx, ssts.SavedSlackTokenQuery, ssts, ssts.inters, v)
}

func (ssts *SavedSlackTokenSelect) sqlScan(ctx context.Context, root *SavedSlackTokenQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ssts.fns))
	for _, fn := range ssts.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ssts.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ssts.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
