// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/nekomeowww/insights-bot/ent/sentmessages"
)

// SentMessagesCreate is the builder for creating a SentMessages entity.
type SentMessagesCreate struct {
	config
	mutation *SentMessagesMutation
	hooks    []Hook
}

// SetChatID sets the "chat_id" field.
func (_c *SentMessagesCreate) SetChatID(v int64) *SentMessagesCreate {
	_c.mutation.SetChatID(v)
	return _c
}

// SetNillableChatID sets the "chat_id" field if the given value is not nil.
func (_c *SentMessagesCreate) SetNillableChatID(v *int64) *SentMessagesCreate {
	if v != nil {
		_c.SetChatID(*v)
	}
	return _c
}

// SetMessageID sets the "message_id" field.
func (_c *SentMessagesCreate) SetMessageID(v int) *SentMessagesCreate {
	_c.mutation.SetMessageID(v)
	return _c
}

// SetNillableMessageID sets the "message_id" field if the given value is not nil.
func (_c *SentMessagesCreate) SetNillableMessageID(v *int) *SentMessagesCreate {
	if v != nil {
		_c.SetMessageID(*v)
	}
	return _c
}

// SetText sets the "text" field.
func (_c *SentMessagesCreate) SetText(v string) *SentMessagesCreate {
	_c.mutation.SetText(v)
	return _c
}

// SetNillableText sets the "text" field if the given value is not nil.
func (_c *SentMessagesCreate) SetNillableText(v *string) *SentMessagesCreate {
	if v != nil {
		_c.SetText(*v)
	}
	return _c
}

// SetIsPinned sets the "is_pinned" field.
func (_c *SentMessagesCreate) SetIsPinned(v bool) *SentMessagesCreate {
	_c.mutation.SetIsPinned(v)
	return _c
}

// SetNillableIsPinned sets the "is_pinned" field if the given value is not nil.
func (_c *SentMessagesCreate) SetNillableIsPinned(v *bool) *SentMessagesCreate {
	if v != nil {
		_c.SetIsPinned(*v)
	}
	return _c
}

// SetFromPlatform sets the "from_platform" field.
func (_c *SentMessagesCreate) SetFromPlatform(v int) *SentMessagesCreate {
	_c.mutation.SetFromPlatform(v)
	return _c
}

// SetNillableFromPlatform sets the "from_platform" field if the given value is not nil.
func (_c *SentMessagesCreate) SetNillableFromPlatform(v *int) *SentMessagesCreate {
	if v != nil {
		_c.SetFromPlatform(*v)
	}
	return _c
}

// SetMessageType sets the "message_type" field.
func (_c *SentMessagesCreate) SetMessageType(v int) *SentMessagesCreate {
	_c.mutation.SetMessageType(v)
	return _c
}

// SetNillableMessageType sets the "message_type" field if the given value is not nil.
func (_c *SentMessagesCreate) SetNillableMessageType(v *int) *SentMessagesCreate {
	if v != nil {
		_c.SetMessageType(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SentMessagesCreate) SetCreatedAt(v int64) *SentMessagesCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SentMessagesCreate) SetNillableCreatedAt(v *int64) *SentMessagesCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SentMessagesCreate) SetUpdatedAt(v int64) *SentMessagesCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SentMessagesCreate) SetNillableUpdatedAt(v *int64) *SentMessagesCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *SentMessagesCreate) SetID(v uuid.UUID) *SentMessagesCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *SentMessagesCreate) SetNillableID(v *uuid.UUID) *SentMessagesCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the SentMessagesMutation object of the builder.
func (_c *SentMessagesCreate) Mutation() *SentMessagesMutation {
	return _c.mutation
}

// Save creates the SentMessages in the database.
func (_c *SentMessagesCreate) Save(ctx context.Context) (*SentMessages, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SentMessagesCreate) SaveX(ctx context.Context) *SentMessages {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SentMessagesCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SentMessagesCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SentMessagesCreate) defaults() {
	if _, ok := _c.mutation.ChatID(); !ok {
		v := sentmessages.DefaultChatID
		_c.mutation.SetChatID(v)
	}
	if _, ok := _c.mutation.MessageID(); !ok {
		v := sentmessages.DefaultMessageID
		_c.mutation.SetMessageID(v)
	}
	if _, ok := _c.mutation.Text(); !ok {
		v := sentmessages.DefaultText
		_c.mutation.SetText(v)
	}
	if _, ok := _c.mutation.IsPinned(); !ok {
		v := sentmessages.DefaultIsPinned
		_c.mutation.SetIsPinned(v)
	}
	if _, ok := _c.mutation.FromPlatform(); !ok {
		v := sentmessages.DefaultFromPlatform
		_c.mutation.SetFromPlatform(v)
	}
	if _, ok := _c.mutation.MessageType(); !ok {
		v := sentmessages.DefaultMessageType
		_c.mutation.SetMessageType(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := sentmessages.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := sentmessages.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := sentmessages.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SentMessagesCreate) check() error {
	if _, ok := _c.mutation.ChatID(); !ok {
		return &ValidationError{Name: "chat_id", err: errors.New(`ent: missing required field "SentMessages.chat_id"`)}
	}
	if _, ok := _c.mutation.MessageID(); !ok {
		return &ValidationError{Name: "message_id", err: errors.New(`ent: missing required field "SentMessages.message_id"`)}
	}
	if _, ok := _c.mutation.Text(); !ok {
		return &ValidationError{Name: "text", err: errors.New(`ent: missing required field "SentMessages.text"`)}
	}
	if _, ok := _c.mutation.IsPinned(); !ok {
		return &ValidationError{Name: "is_pinned", err: errors.New(`ent: missing required field "SentMessages.is_pinned"`)}
	}
	if _, ok := _c.mutation.FromPlatform(); !ok {
		return &ValidationError{Name: "from_platform", err: errors.New(`ent: missing required field "SentMessages.from_platform"`)}
	}
	if _, ok := _c.mutation.MessageType(); !ok {
		return &ValidationError{Name: "message_type", err: errors.New(`ent: missing required field "SentMessages.message_type"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SentMessages.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SentMessages.updated_at"`)}
	}
	return nil
}

func (_c *SentMessagesCreate) sqlSave(ctx context.Context) (*SentMessages, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SentMessagesCreate) createSpec() (*SentMessages, *sqlgraph.CreateSpec) {
	var (
		_node = &SentMessages{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(sentmessages.Table, sqlgraph.NewFieldSpec(sentmessages.FieldID, field.TypeUUID))
	)
	_spec.Schema = _c.schemaConfig.SentMessages
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.ChatID(); ok {
		_spec.SetField(sentmessages.FieldChatID, field.TypeInt64, value)
		_node.ChatID = value
	}
	if value, ok := _c.mutation.MessageID(); ok {
		_spec.SetField(sentmessages.FieldMessageID, field.TypeInt, value)
		_node.MessageID = value
	}
	if value, ok := _c.mutation.Text(); ok {
		_spec.SetField(sentmessages.FieldText, field.TypeString, value)
		_node.Text = value
	}
	if value, ok := _c.mutation.IsPinned(); ok {
		_spec.SetField(sentmessages.FieldIsPinned, field.TypeBool, value)
		_node.IsPinned = value
	}
	if value, ok := _c.mutation.FromPlatform(); ok {
		_spec.SetField(sentmessages.FieldFromPlatform, field.TypeInt, value)
		_node.FromPlatform = value
	}
	if value, ok := _c.mutation.MessageType(); ok {
		_spec.SetField(sentmessages.FieldMessageType, field.TypeInt, value)
		_node.MessageType = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(sentmessages.FieldCreatedAt, field.TypeInt64, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(sentmessages.FieldUpdatedAt, field.TypeInt64, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// SentMessagesCreateBulk is the builder for creating many SentMessages entities in bulk.
type SentMessagesCreateBulk struct {
	config
	err      error
	builders []*SentMessagesCreate
}

// Save creates the SentMessages entities in the database.
func (_c *SentMessagesCreateBulk) Save(ctx context.Context) ([]*SentMessages, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SentMessages, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SentMessagesMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SentMessagesCreateBulk) SaveX(ctx context.Context) []*SentMessages {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SentMessagesCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SentMessagesCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
