// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/nekomeowww/insights-bot/ent/internal"
	"github.com/nekomeowww/insights-bot/ent/predicate"
	"github.com/nekomeowww/insights-bot/ent/slackoauthcredentials"
)

// SlackOAuthCredentialsQuery is the builder for querying SlackOAuthCredentials entities.
type SlackOAuthCredentialsQuery struct {
	config
	ctx        *QueryContext
	order      []slackoauthcredentials.OrderOption
	inters     []Interceptor
	predicates []predicate.SlackOAuthCredentials
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SlackOAuthCredentialsQuery builder.
func (socq *SlackOAuthCredentialsQuery) Where(ps ...predicate.SlackOAuthCredentials) *SlackOAuthCredentialsQuery {
	socq.predicates = append(socq.predicates, ps...)
	return socq
}

// Limit the number of records to be returned by this query.
func (socq *SlackOAuthCredentialsQuery) Limit(limit int) *SlackOAuthCredentialsQuery {
	socq.ctx.Limit = &limit
	return socq
}

// Offset to start from.
func (socq *SlackOAuthCredentialsQuery) Offset(offset int) *SlackOAuthCredentialsQuery {
	socq.ctx.Offset = &offset
	return socq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (socq *SlackOAuthCredentialsQuery) Unique(unique bool) *SlackOAuthCredentialsQuery {
	socq.ctx.Unique = &unique
	return socq
}

// Order specifies how the records should be ordered.
func (socq *SlackOAuthCredentialsQuery) Order(o ...slackoauthcredentials.OrderOption) *SlackOAuthCredentialsQuery {
	socq.order = append(socq.order, o...)
	return socq
}

// First returns the first SlackOAuthCredentials entity from the query.
// Returns a *NotFoundError when no SlackOAuthCredentials was found.
func (socq *SlackOAuthCredentialsQuery) First(ctx context.Context) (*SlackOAuthCredentials, error) {
	nodes, err := socq.Limit(1).All(setContextOp(ctx, socq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{slackoauthcredentials.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (socq *SlackOAuthCredentialsQuery) FirstX(ctx context.Context) *SlackOAuthCredentials {
	node, err := socq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first SlackOAuthCredentials ID from the query.
// Returns a *NotFoundError when no SlackOAuthCredentials ID was found.
func (socq *SlackOAuthCredentialsQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = socq.Limit(1).IDs(setContextOp(ctx, socq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{slackoauthcredentials.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (socq *SlackOAuthCredentialsQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := socq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single SlackOAuthCredentials entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one SlackOAuthCredentials entity is found.
// Returns a *NotFoundError when no SlackOAuthCredentials entities are found.
func (socq *SlackOAuthCredentialsQuery) Only(ctx context.Context) (*SlackOAuthCredentials, error) {
	nodes, err := socq.Limit(2).All(setContextOp(ctx, socq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{slackoauthcredentials.Label}
	default:
		return nil, &NotSingularError{slackoauthcredentials.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (socq *SlackOAuthCredentialsQuery) OnlyX(ctx context.Context) *SlackOAuthCredentials {
	node, err := socq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only SlackOAuthCredentials ID in the query.
// Returns a *NotSingularError when more than one SlackOAuthCredentials ID is found.
// Returns a *NotFoundError when no entities are found.
func (socq *SlackOAuthCredentialsQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = socq.Limit(2).IDs(setContextOp(ctx, socq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{slackoauthcredentials.Label}
	default:
		err = &NotSingularError{slackoauthcredentials.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (socq *SlackOAuthCredentialsQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := socq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SlackOAuthCredentialsSlice.
func (socq *SlackOAuthCredentialsQuery) All(ctx context.Context) ([]*SlackOAuthCredentials, error) {
	ctx = setContextOp(ctx, socq.ctx, "All")
	if err := socq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*SlackOAuthCredentials, *SlackOAuthCredentialsQuery]()
	return withInterceptors[[]*SlackOAuthCredentials](ctx, socq, qr, socq.inters)
}

// AllX is like All, but panics if an error occurs.
func (socq *SlackOAuthCredentialsQuery) AllX(ctx context.Context) []*SlackOAuthCredentials {
	nodes, err := socq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of SlackOAuthCredentials IDs.
func (socq *SlackOAuthCredentialsQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if socq.ctx.Unique == nil && socq.path != nil {
		socq.Unique(true)
	}
	ctx = setContextOp(ctx, socq.ctx, "IDs")
	if err = socq.Select(slackoauthcredentials.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (socq *SlackOAuthCredentialsQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := socq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (socq *SlackOAuthCredentialsQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, socq.ctx, "Count")
	if err := socq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, socq, querierCount[*SlackOAuthCredentialsQuery](), socq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (socq *SlackOAuthCredentialsQuery) CountX(ctx context.Context) int {
	count, err := socq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (socq *SlackOAuthCredentialsQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, socq.ctx, "Exist")
	switch _, err := socq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (socq *SlackOAuthCredentialsQuery) ExistX(ctx context.Context) bool {
	exist, err := socq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SlackOAuthCredentialsQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (socq *SlackOAuthCredentialsQuery) Clone() *SlackOAuthCredentialsQuery {
	if socq == nil {
		return nil
	}
	return &SlackOAuthCredentialsQuery{
		config:     socq.config,
		ctx:        socq.ctx.Clone(),
		order:      append([]slackoauthcredentials.OrderOption{}, socq.order...),
		inters:     append([]Interceptor{}, socq.inters...),
		predicates: append([]predicate.SlackOAuthCredentials{}, socq.predicates...),
		// clone intermediate query.
		sql:  socq.sql.Clone(),
		path: socq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		TeamID string `json:"team_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.SlackOAuthCredentials.Query().
//		GroupBy(slackoauthcredentials.FieldTeamID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (socq *SlackOAuthCredentialsQuery) GroupBy(field string, fields ...string) *SlackOAuthCredentialsGroupBy {
	socq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SlackOAuthCredentialsGroupBy{build: socq}
	grbuild.flds = &socq.ctx.Fields
	grbuild.label = slackoauthcredentials.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		TeamID string `json:"team_id,omitempty"`
//	}
//
//	client.SlackOAuthCredentials.Query().
//		Select(slackoauthcredentials.FieldTeamID).
//		Scan(ctx, &v)
func (socq *SlackOAuthCredentialsQuery) Select(fields ...string) *SlackOAuthCredentialsSelect {
	socq.ctx.Fields = append(socq.ctx.Fields, fields...)
	sbuild := &SlackOAuthCredentialsSelect{SlackOAuthCredentialsQuery: socq}
	sbuild.label = slackoauthcredentials.Label
	sbuild.flds, sbuild.scan = &socq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SlackOAuthCredentialsSelect configured with the given aggregations.
func (socq *SlackOAuthCredentialsQuery) Aggregate(fns ...AggregateFunc) *SlackOAuthCredentialsSelect {
	return socq.Select().Aggregate(fns...)
}

func (socq *SlackOAuthCredentialsQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range socq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, socq); err != nil {
				return err
			}
		}
	}
	for _, f := range socq.ctx.Fields {
		if !slackoauthcredentials.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if socq.path != nil {
		prev, err := socq.path(ctx)
		if err != nil {
			return err
		}
		socq.sql = prev
	}
	return nil
}

func (socq *SlackOAuthCredentialsQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*SlackOAuthCredentials, error) {
	var (
		nodes = []*SlackOAuthCredentials{}
		_spec = socq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*SlackOAuthCredentials).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &SlackOAuthCredentials{config: socq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	_spec.Node.Schema = socq.schemaConfig.SlackOAuthCredentials
	ctx = internal.NewSchemaConfigContext(ctx, socq.schemaConfig)
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, socq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (socq *SlackOAuthCredentialsQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := socq.querySpec()
	_spec.Node.Schema = socq.schemaConfig.SlackOAuthCredentials
	ctx = internal.NewSchemaConfigContext(ctx, socq.schemaConfig)
	_spec.Node.Columns = socq.ctx.Fields
	if len(socq.ctx.Fields) > 0 {
		_spec.Unique = socq.ctx.Unique != nil && *socq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, socq.driver, _spec)
}

func (socq *SlackOAuthCredentialsQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(slackoauthcredentials.Table, slackoauthcredentials.Columns, sqlgraph.NewFieldSpec(slackoauthcredentials.FieldID, field.TypeUUID))
	_spec.From = socq.sql
	if unique := socq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if socq.path != nil {
		_spec.Unique = true
	}
	if fields := socq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, slackoauthcredentials.FieldID)
		for i := range fields {
			if fields[i] != slackoauthcredentials.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := socq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := socq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := socq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := socq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (socq *SlackOAuthCredentialsQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(socq.driver.Dialect())
	t1 := builder.Table(slackoauthcredentials.Table)
	columns := socq.ctx.Fields
	if len(columns) == 0 {
		columns = slackoauthcredentials.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if socq.sql != nil {
		selector = socq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if socq.ctx.Unique != nil && *socq.ctx.Unique {
		selector.Distinct()
	}
	t1.Schema(socq.schemaConfig.SlackOAuthCredentials)
	ctx = internal.NewSchemaConfigContext(ctx, socq.schemaConfig)
	selector.WithContext(ctx)
	for _, p := range socq.predicates {
		p(selector)
	}
	for _, p := range socq.order {
		p(selector)
	}
	if offset := socq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := socq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// SlackOAuthCredentialsGroupBy is the group-by builder for SlackOAuthCredentials entities.
type SlackOAuthCredentialsGroupBy struct {
	selector
	build *SlackOAuthCredentialsQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (socgb *SlackOAuthCredentialsGroupBy) Aggregate(fns ...AggregateFunc) *SlackOAuthCredentialsGroupBy {
	socgb.fns = append(socgb.fns, fns...)
	return socgb
}

// Scan applies the selector query and scans the result into the given value.
func (socgb *SlackOAuthCredentialsGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, socgb.build.ctx, "GroupBy")
	if err := socgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SlackOAuthCredentialsQuery, *SlackOAuthCredentialsGroupBy](ctx, socgb.build, socgb, socgb.build.inters, v)
}

func (socgb *SlackOAuthCredentialsGroupBy) sqlScan(ctx context.Context, root *SlackOAuthCredentialsQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(socgb.fns))
	for _, fn := range socgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*socgb.flds)+len(socgb.fns))
		for _, f := range *socgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*socgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := socgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SlackOAuthCredentialsSelect is the builder for selecting fields of SlackOAuthCredentials entities.
type SlackOAuthCredentialsSelect struct {
	*SlackOAuthCredentialsQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (socs *SlackOAuthCredentialsSelect) Aggregate(fns ...AggregateFunc) *SlackOAuthCredentialsSelect {
	socs.fns = append(socs.fns, fns...)
	return socs
}

// Scan applies the selector query and scans the result into the given value.
func (socs *SlackOAuthCredentialsSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, socs.ctx, "Select")
	if err := socs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SlackOAuthCredentialsQuery, *SlackOAuthCredentialsSelect](ctx, socs.SlackOAuthCredentialsQuery, socs, socs.inters, v)
}

func (socs *SlackOAuthCredentialsSelect) sqlScan(ctx context.Context, root *SlackOAuthCredentialsQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(socs.fns))
	for _, fn := range socs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*socs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := socs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
