// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/nekomeowww/insights-bot/ent/internal"
	"github.com/nekomeowww/insights-bot/ent/predicate"
	"github.com/nekomeowww/insights-bot/ent/slackoauthcredentials"
)

// SlackOAuthCredentialsDelete is the builder for deleting a SlackOAuthCredentials entity.
type SlackOAuthCredentialsDelete struct {
	config
	hooks    []Hook
	mutation *SlackOAuthCredentialsMutation
}

// Where appends a list predicates to the SlackOAuthCredentialsDelete builder.
func (_d *SlackOAuthCredentialsDelete) Where(ps ...predicate.SlackOAuthCredentials) *SlackOAuthCredentialsDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *SlackOAuthCredentialsDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SlackOAuthCredentialsDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *SlackOAuthCredentialsDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(slackoauthcredentials.Table, sqlgraph.NewFieldSpec(slackoauthcredentials.FieldID, field.TypeUUID))
	_spec.Node.Schema = _d.schemaConfig.SlackOAuthCredentials
	ctx = internal.NewSchemaConfigContext(ctx, _d.schemaConfig)
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// SlackOAuthCredentialsDeleteOne is the builder for deleting a single SlackOAuthCredentials entity.
type SlackOAuthCredentialsDeleteOne struct {
	_d *SlackOAuthCredentialsDelete
}

// Where appends a list predicates to the SlackOAuthCredentialsDelete builder.
func (_d *SlackOAuthCredentialsDeleteOne) Where(ps ...predicate.SlackOAuthCredentials) *SlackOAuthCredentialsDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *SlackOAuthCredentialsDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{slackoauthcredentials.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SlackOAuthCredentialsDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
