// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/nekomeowww/insights-bot/ent/internal"
	"github.com/nekomeowww/insights-bot/ent/predicate"
	"github.com/nekomeowww/insights-bot/ent/telegramchatautorecapssubscribers"
)

// TelegramChatAutoRecapsSubscribersUpdate is the builder for updating TelegramChatAutoRecapsSubscribers entities.
type TelegramChatAutoRecapsSubscribersUpdate struct {
	config
	hooks    []Hook
	mutation *TelegramChatAutoRecapsSubscribersMutation
}

// Where appends a list predicates to the TelegramChatAutoRecapsSubscribersUpdate builder.
func (_u *TelegramChatAutoRecapsSubscribersUpdate) Where(ps ...predicate.TelegramChatAutoRecapsSubscribers) *TelegramChatAutoRecapsSubscribersUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetChatID sets the "chat_id" field.
func (_u *TelegramChatAutoRecapsSubscribersUpdate) SetChatID(v int64) *TelegramChatAutoRecapsSubscribersUpdate {
	_u.mutation.ResetChatID()
	_u.mutation.SetChatID(v)
	return _u
}

// SetNillableChatID sets the "chat_id" field if the given value is not nil.
func (_u *TelegramChatAutoRecapsSubscribersUpdate) SetNillableChatID(v *int64) *TelegramChatAutoRecapsSubscribersUpdate {
	if v != nil {
		_u.SetChatID(*v)
	}
	return _u
}

// AddChatID adds value to the "chat_id" field.
func (_u *TelegramChatAutoRecapsSubscribersUpdate) AddChatID(v int64) *TelegramChatAutoRecapsSubscribersUpdate {
	_u.mutation.AddChatID(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *TelegramChatAutoRecapsSubscribersUpdate) SetUserID(v int64) *TelegramChatAutoRecapsSubscribersUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *TelegramChatAutoRecapsSubscribersUpdate) SetNillableUserID(v *int64) *TelegramChatAutoRecapsSubscribersUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *TelegramChatAutoRecapsSubscribersUpdate) AddUserID(v int64) *TelegramChatAutoRecapsSubscribersUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *TelegramChatAutoRecapsSubscribersUpdate) SetCreatedAt(v int64) *TelegramChatAutoRecapsSubscribersUpdate {
	_u.mutation.ResetCreatedAt()
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *TelegramChatAutoRecapsSubscribersUpdate) SetNillableCreatedAt(v *int64) *TelegramChatAutoRecapsSubscribersUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// AddCreatedAt adds value to the "created_at" field.
func (_u *TelegramChatAutoRecapsSubscribersUpdate) AddCreatedAt(v int64) *TelegramChatAutoRecapsSubscribersUpdate {
	_u.mutation.AddCreatedAt(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TelegramChatAutoRecapsSubscribersUpdate) SetUpdatedAt(v int64) *TelegramChatAutoRecapsSubscribersUpdate {
	_u.mutation.ResetUpdatedAt()
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *TelegramChatAutoRecapsSubscribersUpdate) SetNillableUpdatedAt(v *int64) *TelegramChatAutoRecapsSubscribersUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// AddUpdatedAt adds value to the "updated_at" field.
func (_u *TelegramChatAutoRecapsSubscribersUpdate) AddUpdatedAt(v int64) *TelegramChatAutoRecapsSubscribersUpdate {
	_u.mutation.AddUpdatedAt(v)
	return _u
}

// Mutation returns the TelegramChatAutoRecapsSubscribersMutation object of the builder.
func (_u *TelegramChatAutoRecapsSubscribersUpdate) Mutation() *TelegramChatAutoRecapsSubscribersMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TelegramChatAutoRecapsSubscribersUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TelegramChatAutoRecapsSubscribersUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TelegramChatAutoRecapsSubscribersUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TelegramChatAutoRecapsSubscribersUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *TelegramChatAutoRecapsSubscribersUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(telegramchatautorecapssubscribers.Table, telegramchatautorecapssubscribers.Columns, sqlgraph.NewFieldSpec(telegramchatautorecapssubscribers.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ChatID(); ok {
		_spec.SetField(telegramchatautorecapssubscribers.FieldChatID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedChatID(); ok {
		_spec.AddField(telegramchatautorecapssubscribers.FieldChatID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(telegramchatautorecapssubscribers.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(telegramchatautorecapssubscribers.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(telegramchatautorecapssubscribers.FieldCreatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedAt(); ok {
		_spec.AddField(telegramchatautorecapssubscribers.FieldCreatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(telegramchatautorecapssubscribers.FieldUpdatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdatedAt(); ok {
		_spec.AddField(telegramchatautorecapssubscribers.FieldUpdatedAt, field.TypeInt64, value)
	}
	_spec.Node.Schema = _u.schemaConfig.TelegramChatAutoRecapsSubscribers
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{telegramchatautorecapssubscribers.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TelegramChatAutoRecapsSubscribersUpdateOne is the builder for updating a single TelegramChatAutoRecapsSubscribers entity.
type TelegramChatAutoRecapsSubscribersUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TelegramChatAutoRecapsSubscribersMutation
}

// SetChatID sets the "chat_id" field.
func (_u *TelegramChatAutoRecapsSubscribersUpdateOne) SetChatID(v int64) *TelegramChatAutoRecapsSubscribersUpdateOne {
	_u.mutation.ResetChatID()
	_u.mutation.SetChatID(v)
	return _u
}

// SetNillableChatID sets the "chat_id" field if the given value is not nil.
func (_u *TelegramChatAutoRecapsSubscribersUpdateOne) SetNillableChatID(v *int64) *TelegramChatAutoRecapsSubscribersUpdateOne {
	if v != nil {
		_u.SetChatID(*v)
	}
	return _u
}

// AddChatID adds value to the "chat_id" field.
func (_u *TelegramChatAutoRecapsSubscribersUpdateOne) AddChatID(v int64) *TelegramChatAutoRecapsSubscribersUpdateOne {
	_u.mutation.AddChatID(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *TelegramChatAutoRecapsSubscribersUpdateOne) SetUserID(v int64) *TelegramChatAutoRecapsSubscribersUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *TelegramChatAutoRecapsSubscribersUpdateOne) SetNillableUserID(v *int64) *TelegramChatAutoRecapsSubscribersUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *TelegramChatAutoRecapsSubscribersUpdateOne) AddUserID(v int64) *TelegramChatAutoRecapsSubscribersUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *TelegramChatAutoRecapsSubscribersUpdateOne) SetCreatedAt(v int64) *TelegramChatAutoRecapsSubscribersUpdateOne {
	_u.mutation.ResetCreatedAt()
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *TelegramChatAutoRecapsSubscribersUpdateOne) SetNillableCreatedAt(v *int64) *TelegramChatAutoRecapsSubscribersUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// AddCreatedAt adds value to the "created_at" field.
func (_u *TelegramChatAutoRecapsSubscribersUpdateOne) AddCreatedAt(v int64) *TelegramChatAutoRecapsSubscribersUpdateOne {
	_u.mutation.AddCreatedAt(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TelegramChatAutoRecapsSubscribersUpdateOne) SetUpdatedAt(v int64) *TelegramChatAutoRecapsSubscribersUpdateOne {
	_u.mutation.ResetUpdatedAt()
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *TelegramChatAutoRecapsSubscribersUpdateOne) SetNillableUpdatedAt(v *int64) *TelegramChatAutoRecapsSubscribersUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// AddUpdatedAt adds value to the "updated_at" field.
func (_u *TelegramChatAutoRecapsSubscribersUpdateOne) AddUpdatedAt(v int64) *TelegramChatAutoRecapsSubscribersUpdateOne {
	_u.mutation.AddUpdatedAt(v)
	return _u
}

// Mutation returns the TelegramChatAutoRecapsSubscribersMutation object of the builder.
func (_u *TelegramChatAutoRecapsSubscribersUpdateOne) Mutation() *TelegramChatAutoRecapsSubscribersMutation {
	return _u.mutation
}

// Where appends a list predicates to the TelegramChatAutoRecapsSubscribersUpdate builder.
func (_u *TelegramChatAutoRecapsSubscribersUpdateOne) Where(ps ...predicate.TelegramChatAutoRecapsSubscribers) *TelegramChatAutoRecapsSubscribersUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TelegramChatAutoRecapsSubscribersUpdateOne) Select(field string, fields ...string) *TelegramChatAutoRecapsSubscribersUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TelegramChatAutoRecapsSubscribers entity.
func (_u *TelegramChatAutoRecapsSubscribersUpdateOne) Save(ctx context.Context) (*TelegramChatAutoRecapsSubscribers, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TelegramChatAutoRecapsSubscribersUpdateOne) SaveX(ctx context.Context) *TelegramChatAutoRecapsSubscribers {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TelegramChatAutoRecapsSubscribersUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TelegramChatAutoRecapsSubscribersUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *TelegramChatAutoRecapsSubscribersUpdateOne) sqlSave(ctx context.Context) (_node *TelegramChatAutoRecapsSubscribers, err error) {
	_spec := sqlgraph.NewUpdateSpec(telegramchatautorecapssubscribers.Table, telegramchatautorecapssubscribers.Columns, sqlgraph.NewFieldSpec(telegramchatautorecapssubscribers.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TelegramChatAutoRecapsSubscribers.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, telegramchatautorecapssubscribers.FieldID)
		for _, f := range fields {
			if !telegramchatautorecapssubscribers.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != telegramchatautorecapssubscribers.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ChatID(); ok {
		_spec.SetField(telegramchatautorecapssubscribers.FieldChatID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedChatID(); ok {
		_spec.AddField(telegramchatautorecapssubscribers.FieldChatID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(telegramchatautorecapssubscribers.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(telegramchatautorecapssubscribers.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(telegramchatautorecapssubscribers.FieldCreatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedAt(); ok {
		_spec.AddField(telegramchatautorecapssubscribers.FieldCreatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(telegramchatautorecapssubscribers.FieldUpdatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdatedAt(); ok {
		_spec.AddField(telegramchatautorecapssubscribers.FieldUpdatedAt, field.TypeInt64, value)
	}
	_spec.Node.Schema = _u.schemaConfig.TelegramChatAutoRecapsSubscribers
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	_node = &TelegramChatAutoRecapsSubscribers{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{telegramchatautorecapssubscribers.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
